[package]
name = "view3d"
version = "0.1.0"
authors = ["Jake O'Shannessy <joshannessy@gmail.com>"]
build = "build.rs"

[dependencies]
clap = "~2.32.0"
time = "0.1"
libc = "0.2.0"

[build-dependencies]
cc = "1.0"
