version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt-get update
            apt-get install gcc make -y
      - run:
          name: Build lib
          command: make lib
      - run:
          name: Build binaries
          command: make
      - run:
          name: Setup Rust
          command: |
            apt-get install curl -y
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
      - run:
          name: Build Rust binaries
          command: cargo build
