version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt-get update
            apt-get install gcc make -y
      - run:
          name: Build lib
          command: make lib
      - run:
          name: Build binaries
          command: make
      - run:
          name: Setup Rust
          command: |
            apt-get install curl -y
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
      - run:
          name: Build Rust binaries
          command: |
            source $HOME/.cargo/env
            cargo build
  build-cmake:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt-get update
            apt-get install gcc g++ make cmake -y
      - run:
          name: Build binaries
          command: |
            mkdir build-dir
            cd build-dir
            cmake ..
            make
  build-rust:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt-get update
            apt-get install gcc make -y
      - run:
          name: Setup Rust
          command: |
            apt-get install curl -y
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
      - run:
          name: Build Rust binaries
          command: |
            source $HOME/.cargo/env
            cargo build
  test-rust:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt-get update
            apt-get install gcc make -y
      - run:
          name: Setup Rust
          command: |
            apt-get install curl -y
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
      - run:
          name: Build Rust binaries
          command: |
            source $HOME/.cargo/env
            cargo test

workflows:
  version: 2
  build-testing:
    jobs:
      - build
      - build-cmake
      - build-rust
      - test-rust
