version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Setup
          command: apt-get install build-essential
      - run:
          name: Build lib
          command: make lib
      - run:
          name: Build binaries
          command: make
