Import('env')

cav_env = env.Copy()
cav_env.AppendUnique(
	LIBS = env.get('SOQT_LIBS')
	, LIBPATH = env.get('SOQT_LIBPATH')
	, CPPPATH = env.get('SOQT_CPPPATH')
	, CPPDEFINES = env.get('SOQT_CPPDEFINES')
)

cav_env.Program('cavity',['cavity.cpp'])
